pages/index.tsx

chore: 필요없는 코드 삭제

---

apps/web/components/register/InterestSection.tsx

- 기존 코드 리팩토링
- 관심사 선택 페이지 퍼블리싱 완료
- 참고 사항1

[CZ-210]: 관심사 선택 페이지 퍼블리싱 완료

---

apps/web/components/post/ImageTitleSection.tsx
apps/web/pages/post/index.tsx
apps/web/services/usePostVoteService.ts
apps/web/styled-compoenets.d.ts

- 테마 자동완성 
- 투표 글쓰기 반응형 처리 
- auto assign 을 고치는 중입니다

Cz 226 post vote page

---

apps/web/lib/constants.ts

배포환경에서 social login을 위한 redirect url 설정

---

apps/web/components/select/MenuBox.tsx
apps/web/components/select/SelectAB.tsx
apps/web/components/select/hooks/useFlipAnimation.ts
apps/web/pages/select/[id].tsx
package/ui/styles/transitions.ts

[CZ-293] 투표 카드 플립 애니메이션 적용

---

apps/web.code-workspace
apps/web/lib/constants.ts
apps/web/pages/register/interest.tsx

- pageInner height값을 수정
- web.code-workspace 파일 추가
- 여러 배포 환경 유지를 위해 client url을 .env 파일로부터 받도록 constant 파일 수정
- 참고 사항1

[CZ-333] 카테고리 선택 페이지 퍼블리싱 수정 및 프로젝트 세팅 수정 

---

apps/web/components/register/AgeSelection.tsx
apps/web/services/useRegisterService.ts

- 2개 이상의 숫자를 클릭 했을 때 마지막 두 숫자가 남도록 수정
- 간격 수정
- if문을 쓸지 switch문을 쓸지 살짝 고민이 됩니다.
`    if (!userInfo.age) {
setUserInfo((prev) => ({ ...prev, age: innerText }));
} else if (userInfo.age.length === 1) {
setUserInfo((prev) => ({ ...prev, age: prev.age + innerText }));
} else if (userInfo.age.length === 2) {
setUserInfo((prev) => ({ ...prev, age: prev.age?.substring(1) + innerText }));
}`

[CZ-334] 나이 선택 페이지에서 2개 이상의 숫자를 클릭 했을 때 마지막 두 숫자가 남도록 수정

---

apps/web/.vscode/settings.json
apps/web/app/select/[id]/detail/page.tsx
apps/web/app/select/[id]/page.tsx
apps/web/components/detail/DetailAB.tsx
apps/web/components/detail/FilterBar.tsx
apps/web/components/detail/VoteAnalyzeBar.tsx
apps/web/components/select/SelectAB.tsx
apps/web/components/select/VoteToolbar.tsx
apps/web/tsconfig.json

Cz 359 detail page publishing

---

apps/web/.vscode/settings.json
apps/web/app/select/[id]/detail/page.tsx
apps/web/app/select/[id]/page.tsx
apps/web/components/detail/DetailAB.tsx
apps/web/components/detail/FilterBar.tsx
apps/web/components/detail/VoteAnalyzeBar.tsx
apps/web/components/select/SelectAB.tsx
apps/web/components/select/VoteToolbar.tsx
apps/web/tsconfig.json

- 디테일 페이지 퍼블리싱
- #49 와 동일한 pr입니다

[CZ-359] 디테일 페이지 퍼블리싱

---

apps/web/components/post/ImageTitleSection.tsx

- 투표 생성 qa 퍼블리싱 부분 진행
- 일부 진행하다가 메인페이지 우선 하는게 좋을거 같다고 하여 여기까지 하고 나머지는 나중에 진행하겠습니다.

[CZ-372] 이미지 타이틀 파트 디자인 QA

---

apps/web/app/voteList/page.tsx
apps/web/components/common/select/index.ts
apps/web/components/voteList/CategorySelectBox.tsx
apps/web/components/voteList/SortSelectBox.tsx
apps/web/components/voteList/index.ts
apps/web/lib/constants.ts
apps/web/public/icons/SelectDropdownIndicator.svg
apps/web/public/icons/index.ts
apps/web/tsconfig.json
packages/ui/components/index.ts
packages/ui/components/selectBox/Option.tsx
packages/ui/components/selectBox/OptionList.tsx
packages/ui/components/selectBox/SelectButton.tsx
packages/ui/components/selectBox/hooks/index.ts
packages/ui/components/selectBox/hooks/useSelect.ts
packages/ui/components/selectBox/index.ts
packages/ui/styles/theme.ts

- select box ui 패키지로 마이그레이션
- 정렬 select box 구현
- 지금 디벨롭 브랜치에서 배포 에러 발생하고 있는데 이 브랜치 머지되면 해결될 것 같습니다.

[CZ-381] 정렬 select box 구현

---

apps/web/components/voteList/CategorySelect.tsx
apps/web/components/voteList/SortSelect.tsx
packages/ui/components/selectBox/Option.tsx
packages/ui/components/selectBox/OptionList.tsx
packages/ui/components/selectBox/Select.tsx
packages/ui/components/selectBox/SelectButton.tsx

- select 컴포넌트 리팩터링
- 리팩터링에 따른 category select, sort select 수정
- select 컴포넌트 코드가 아직도 깔끔하지 못한 것 같습니다.

[CZ-417] 정렬 셀렉트 박스 테두리 수정

---

apps/web/components/voteList/CategorySelect.tsx
apps/web/components/voteList/SortSelect.tsx
apps/web/types/vote.ts
packages/ui/components/selectBox/Select.tsx

- 중복되어 있는 타입 수정
- select box에 indicator 방향이 바뀌도록 수정
-

[CZ-420] select box에 indicator 방향이 바뀌도록 수정

---

apps/web/app/select/[id]/page.tsx
apps/web/components/select/AddDetailModal.tsx
apps/web/components/select/SelectAB.tsx
apps/web/lib/apis/vote.ts
apps/web/services/useModifyVoteService.ts

- 2차 투표생성 api에 실제 데이터 넣어 작동되도록 변경
-

[CZ-424] 2차 투표생성 api 유효값으로 변경

---

apps/web/components/voteList/VoteItem.tsx

- 이미지 사이 간격 제거
- 양 끝에만 radius 처리
-

[CZ-425] 이미지 형태 수정

---

apps/web/services/useModifyVoteService.ts

[CZ-434] 객체 분해 할당 오류 해결

---

apps/web/app/login/kakaoLoginProcess/page.tsx
apps/web/app/login/naverLoginProcess/page.tsx
apps/web/hooks/useGetUserInfo.ts
apps/web/services/useRegisterService.ts

- 사용하지 않는 queryClient 삭제
- react query를 사용하여 유저 정보를 가져오는 훅 추가
- 만약 유저 정보가 변경될 경우 `queryClient.invalidateQueries({ queryKey: ['userInfo'] })`를 사용해주면 됩니다.
- https://stackoverflow.com/questions/71282427/how-to-fetch-user-details-only-once

[CZ-442] react query를 사용하여 유저 정보를 가져오는 훅 추가

---

apps/web/app/my/page.tsx
apps/web/hooks/useGetUserInfo.ts
apps/web/lib/apis/user.ts
apps/web/lib/apis/vote.ts
apps/web/lib/queryKeys.ts
apps/web/services/useInfiniteMyPageVoteListService.ts
apps/web/types/user.ts

- 유저 정보 연동
- 탭에따른 vote list 연동
- 투표 갯수 연동
- 코드가 많이 더럽습니다. 추후 리팩토링 하겠습니다.

[CZ-460] 마이페이지 api 연동

---

apps/web/app/my/edit/page.tsx
apps/web/app/my/page.tsx
apps/web/components/common/ImageUploadButton.tsx
apps/web/components/detail/FilterBar.tsx
apps/web/components/my/MbtiSelect.tsx
apps/web/components/my/TabContainer.tsx
apps/web/components/post/TargetSection.tsx
apps/web/lib/Path.ts
apps/web/lib/constants.ts

- 마이페이지에서 사용하는 tab 분리
- image 업로드 버튼 공용 컴포넌트화
- mbti select 구현
- image upload button 로직을 분리하지 못했습니다.

[CZ-448] 프로필 편집 페이지 퍼블리싱

---

apps/web/components/detail/CommentContainer.tsx
apps/web/components/detail/VoteAnalyzeBar.tsx
apps/web/components/detail/VoteContainer.tsx
apps/web/lib/apis/comments.ts
packages/ui/components/button/Button.tsx

- 댓글 기존 다불러오는것에서 -> 무한 더보기로 변경
- 통계 로직 선택한거에서 더많이 선택한 보기로 수정
- 
-

[CZ-459] 통계 로직 변경, 댓글 무한 더보기 수정

---

apps/web/app/my/edit/page.tsx
apps/web/app/my/page.tsx
apps/web/components/common/ImageUploadButton.tsx
apps/web/components/post/ImageTitleSection.tsx
apps/web/components/register/InterestSection.tsx
apps/web/hooks/useGetUserInfo.ts
apps/web/lib/apis/user.ts
apps/web/types/user.ts

- 프로필 수정 api 적용
- useGetUserInfo에서 useState를 사용했고, 그 값을 리턴받아서 썼는데 이로인해 버그가 발생하고 있는 것 같습니다. https://chooz.atlassian.net/jira/software/projects/CZ/boards/1/backlog?assignee=6135b8ca7eb35f0069148d61&selectedIssue=CZ-479

[CZ-472] 프로필 편집 페이지 api 연동

---

apps/web/components/detail/DetailAB.tsx
apps/web/components/detail/FilterBar.tsx
apps/web/components/detail/VoteContainer.tsx

- 투표 한 채로 detail 진입시 결과 통계값 나오도록 수정
- 필터 chip 퍼블리싱 작동하게만 수정
- 참고 사항1

[CZ-478] 투표 통계치 표시

---

apps/web/components/detail/CommentContainer.tsx
apps/web/components/detail/DetailAB.tsx
apps/web/services/useMutateCommentService.ts
apps/web/services/useMutateVotingService.ts

- 댓글 쓰고 초기화 기능
- 투표하고 내 투표 반영된 통계가 뜨도록 수정
- 자세히 보기 버튼 위치 수정
- 기타 qa
- qa부터 하려고 했지만 어제 회의 내용상 튜토리얼을 먼저 해야할거 같아 푸시하고 다음꺼 진행하겠습니다

[CZ-483] 디테일 페이지 qa

---

apps/web/components/detail/FilterBar.tsx
apps/web/components/detail/VoteContainer.tsx
apps/web/components/detail/hooks/useFilterStatistics.ts
apps/web/lib/apis/vote.ts
apps/web/lib/queryKeys.ts
apps/web/services/useFilteredStatisticsService.ts
apps/web/types/vote.ts

[CZ-497] filtered statistics 구현

---

apps/web/hooks/useReplaceUser.ts

[CZ-499] 로그인 페이지로 강제 이동시켜주던 버그 수정

---

apps/web/app/page.tsx
apps/web/lib/apis/vote.ts

- 선택 페이지에서 상세 페이지로 연결되지 않던 버그 수정
- 상세 페이지에서 통계를 불러오지 못해 ui를 띄우지 못하던 버그 수정
-

[CZ-502] 선택 페이지, 상세 페이지 버그 수정

---

apps/web/app/page.tsx
apps/web/components/select/hooks/useFlipAnimation.ts
apps/web/lib/apis/comments.ts
apps/web/services/useInfiniteMainListService.ts
apps/web/services/useMutateVotingService.ts

- 투표후 즉각 업데이트 되도록 수정 (로그인 안된 상태에서 투표 되는거처럼 보이는것도 수정)
- 모바일에서 스와이프 되도록 수정
- 이벤트 중복 실행 막기
- 
-

[CZ-508] 메인페이지 버그 수정

---

apps/web/app/page.tsx
apps/web/components/detail/VoteContainer.tsx
apps/web/components/select/VoteToolbar.tsx
apps/web/services/usePostVoteService.ts

- post 페이지 연동
- 작업 사항 2
- 참고 사항1

[CZ-525] 메인 페이지 qa 작업

---

apps/web/app/layout.tsx
apps/web/app/page.tsx
apps/web/services/useInfiniteMainListService.ts

- 잘못된 인덱스로 인하여 맨 마지막 투표 도달시 에러 발생하는 부분 수정
- 메인 페이지에서 스크롤이 동작하지 않도록 수정
-

[CZ-526]  메인 페이지 qa 작업 

---

README.md

[CZ-530] 리드미 추가

---

apps/web/app/page.tsx
apps/web/components/select/MenuBox.tsx
apps/web/components/select/VoteToolbar.tsx

- writer id 와 user id 를 비교하여 같을 때만 버튼 노출 구현
- .

[CZ-532] 글 작성자에게만 글 수정, 삭제 권한 부여

---

apps/web/app/page.tsx
apps/web/components/select/MenuBox.tsx
apps/web/components/select/VoteToolbar.tsx

- 작성자에게만 수정,삭제 버튼 노출 되도록 수정
- 참고 사항1

[CZ-532] 작성자에게만 수정,삭제 버튼 노출 되도록 수정

---

apps/web/app/page.tsx
apps/web/app/select/components/ChipContainer.tsx
apps/web/app/select/components/ModifyDeleteButtonBox.tsx
apps/web/app/select/components/ModifyVoteModal.tsx
apps/web/app/select/components/PostCompleteComponent.tsx
apps/web/app/select/components/SelectAorBContainer.tsx
apps/web/app/select/components/UpdateVoteModal.tsx
apps/web/app/select/hooks/useFlipAnimation.ts
apps/web/components/detail/Comment.tsx
apps/web/components/detail/VoteContainer.tsx
apps/web/lib/apis/vote.ts
apps/web/services/useModifyVoteService.ts
apps/web/services/useMutateVotingService.ts
packages/ui/components/index.ts
packages/ui/components/modal/FloatComponentTemplate.tsx

- 보다 나은 코드 퀄리티를 위한 리팩토링
- 투표 삭제 api 연동
- 로그인하지 않은 유저 투표시 alert로 안내
- main(select) 페이지 더 깔끔하게 리팩토링하고 싶습니다.

[CZ-531] main page qa 사항 작업

---

apps/web/app/post/page.tsx
apps/web/components/post/ImageTitleSection.tsx
apps/web/components/post/TargetSection.tsx
apps/web/services/useModifyVoteService.ts

- 투표 수정하면 업데이트가 안되는 현상 수정
- 참고 사항1

[CZ-534] 투표 수정시 즉각 업데이트 안되는 현상 수정

---

apps/web/app/layout.tsx
apps/web/app/page.tsx
apps/web/app/select/components/ModifyVoteModal.tsx
apps/web/app/select/hooks/useFlipAnimation.ts
apps/web/components/detail/CommentContainer.tsx
apps/web/components/detail/VoteContainer.tsx
apps/web/lib/apis/vote.ts
apps/web/services/useModifyVoteService.ts

- 모바일 웹에서 스크롤이 동작하지 않도록 수정
- setUp, setDown 둘 다 -1로 적용되어 있던 부분 수정
- 간단히 보기 클릭시 메인 페이지로 이동하도록 수정
- 모든 페이지에서 공통 마진을 가질 수 있도록 수정
-

[CZ-533] 메인 페이지 qa 작업

---

.pnp.cjs
apps/jurumarble/package.json
apps/jurumarble/src/app/search/page.tsx
apps/jurumarble/src/components/BottomBar.tsx
apps/jurumarble/src/lib/styles/StyledComponents.tsx
apps/jurumarble/src/lib/styles/theme.ts
yarn.lock

- 검색페이지 생성
- 검색 상단 인풋 박스 구현
- 퍼블리싱 진행되었습니다
1

[JR-622] 검색페이지 상단 퍼블리싱

---

.pnp.cjs
apps/jurumarble/package.json
apps/jurumarble/src/app/layout.tsx
apps/jurumarble/src/app/vote/[id]/components/ChipContainer.tsx
apps/jurumarble/src/app/vote/[id]/page.tsx
apps/jurumarble/src/app/vote/components/MenuBox.tsx
apps/jurumarble/src/app/vote/page.tsx
apps/jurumarble/src/app/vote/post/services/useBookmarkService.ts
apps/jurumarble/src/app/vote/post/services/useGetVoteListService.tsx
apps/jurumarble/src/assets/icons/components/IcBookmarkActive.tsx
apps/jurumarble/src/assets/icons/components/index.ts
apps/jurumarble/src/lib/Path.ts
apps/jurumarble/src/lib/apis/bookmark.ts
apps/jurumarble/src/lib/apis/common.ts
apps/jurumarble/src/lib/apis/http.ts
apps/jurumarble/src/lib/apis/vote.ts
apps/jurumarble/src/lib/queryKeys.ts
apps/jurumarble/src/lib/styles/globalStyles.ts
yarn.lock

- 투표 리스트 api 연동
- 북마크 api 연동
- https에 타입 지정 되있던거 지웠는데 괜찮은지?

[JR-728] 투표홈 api 연동

---

apps/jurumarble/src/app/page.tsx
apps/jurumarble/src/app/search/components/DrinkItem.tsx
apps/jurumarble/src/app/search/components/DrinkList.tsx
apps/jurumarble/src/app/stemp/components/DrinkItem.tsx
apps/jurumarble/src/app/stemp/components/DrinkStempContainer.tsx
apps/jurumarble/src/app/stemp/components/MyEnjoiedDrinkInfoSection.tsx
apps/jurumarble/src/app/stemp/components/StempedDrinkList.tsx
apps/jurumarble/src/app/stemp/page.tsx
apps/jurumarble/src/app/stemp/service/useDrinkStempListService.ts
apps/jurumarble/src/app/stemp/service/useDrinkStempService.ts
apps/jurumarble/src/app/vote/post/components/DrinkItem.tsx
apps/jurumarble/src/app/vote/post/components/DrinkSearchModal.tsx
apps/jurumarble/src/components/Header.tsx
apps/jurumarble/src/hooks/useGetDrinkList.ts
apps/jurumarble/src/lib/apis/drink.ts
apps/jurumarble/src/lib/queryKeys.ts
apps/jurumarble/src/types/drink.ts
apps/jurumarble/src/types/vote.ts

- 술도장 페이지 api 연동
- 도장 여부 낙관적 업데이트로 구현
- 디자인에 맞게 헤더 높이 수정
-

[JR-761] 술도장 페이지 api 연동

---

apps/jurumarble/src/app/vote/[id]/components/Comment.tsx
apps/jurumarble/src/app/vote/[id]/components/CommentContainer.tsx
apps/jurumarble/src/app/vote/[id]/components/CommentToolbar.tsx
apps/jurumarble/src/app/vote/[id]/components/VoteAnalyzeBar.tsx
apps/jurumarble/src/app/vote/[id]/components/VoteDescription.tsx
apps/jurumarble/src/app/vote/[id]/components/VoteWriterBox.tsx
apps/jurumarble/src/app/vote/[id]/page.tsx
apps/jurumarble/src/app/vote/[id]/services/useExecuteVoteService.ts
apps/jurumarble/src/app/vote/[id]/services/useFilterStatisticsService.ts
apps/jurumarble/src/lib/apis/comment.ts
apps/jurumarble/src/lib/apis/statistics.ts
apps/jurumarble/src/lib/apis/vote.ts
apps/jurumarble/src/lib/queryKeys.ts

- 투표 댓글 작성자 구현 (현재 유저 데이터에 mbit, age 안적혀져 있어서 이상하게 뜸)
- 투표 통계 구현
- 참고 사항1

[JR-786] 투표 댓글 작성자 구현,투표 통계 구현

---

apps/jurumarble/src/app/my/components/ChipContainer.tsx
apps/jurumarble/src/app/my/components/UseInfoContainer.tsx
apps/jurumarble/src/app/my/components/VoteCountContainer.tsx
apps/jurumarble/src/app/my/components/VoteDescription.tsx
apps/jurumarble/src/app/my/components/VoteItem.tsx
apps/jurumarble/src/app/my/components/VoteListContainer.tsx
apps/jurumarble/src/app/my/page.tsx
apps/jurumarble/src/app/my/services/useGetMyBookmarkedVoteListService.ts
apps/jurumarble/src/app/my/services/useGetMyCreatedVoteListService.ts
apps/jurumarble/src/app/my/services/useGetMyParticipatedVoteListService.ts
apps/jurumarble/src/app/search/components/DrinkVoteItem.tsx
apps/jurumarble/src/app/search/components/SearchContainer.tsx
apps/jurumarble/src/app/vote/post/components/PostVoteContainer.tsx
apps/jurumarble/src/components/AorBMark.tsx
apps/jurumarble/src/components/Header.tsx
apps/jurumarble/src/components/RegionSelect.tsx
apps/jurumarble/src/components/selectBox/OptionList.tsx
apps/jurumarble/src/hooks/useCreateQueryString.ts
apps/jurumarble/src/lib/apis/my.ts
apps/jurumarble/src/lib/apis/user.ts
apps/jurumarble/src/lib/apis/vote.ts
apps/jurumarble/src/lib/constants.ts
apps/jurumarble/src/lib/queryKeys.ts
apps/jurumarble/src/services/useGetUserInfo.ts
apps/jurumarble/src/types/my.ts
apps/jurumarble/src/types/vote.ts

[JR-771] 마이페이지 구현

---

apps/jurumarble/public/IcCheck.svg
apps/jurumarble/src/app/my/edit/components/UserInfoEditContainer.tsx
apps/jurumarble/src/app/my/edit/components/WithdrawalModal.tsx
apps/jurumarble/src/app/my/edit/services/useEditProfileService.ts
apps/jurumarble/src/components/button/Button.tsx
apps/jurumarble/src/lib/apis/my.ts

[JR-811] 회원탈퇴 구현

---

apps/jurumarble/src/app/drink-info/[id]/components/DrinkInfoContainer.tsx
apps/jurumarble/src/app/drink-info/[id]/page.tsx
apps/jurumarble/src/app/drink-info/[id]/services/useDrinkLoadService.ts
apps/jurumarble/src/app/vote/[id]/components/VoteDescription.tsx
apps/jurumarble/src/app/vote/[id]/page.tsx
apps/jurumarble/src/app/vote/page.tsx
apps/jurumarble/src/components/BottomBar.tsx
apps/jurumarble/src/lib/apis/drink.ts
apps/jurumarble/src/lib/queryKeys.ts

- 술인포 구현
- 댓글은 투표와 동일하여 투표꺼 하면서 같이 적용

[JR-739] 술인포 구현

---

apps/jurumarble/src/app/drink-info/[id]/components/DrinkCommentContainer.tsx
apps/jurumarble/src/app/drink-info/[id]/components/DrinkInfoContainer.tsx
apps/jurumarble/src/app/drink-info/[id]/page.tsx
apps/jurumarble/src/app/vote/[id]/components/ChipContainer.tsx
apps/jurumarble/src/app/vote/[id]/components/VoteDescription.tsx
apps/jurumarble/src/app/vote/[id]/page.tsx
apps/jurumarble/src/app/vote/page.tsx

[JR-851] 술인포 댓글 구현

---

apps/jurumarble/src/app/drink-info/[id]/components/DrinkCommentContainer.tsx
apps/jurumarble/src/app/vote/[id]/components/AlcholLevelTag.tsx
apps/jurumarble/src/app/vote/[id]/components/Comment.tsx
apps/jurumarble/src/app/vote/[id]/components/CommentContainer.tsx
apps/jurumarble/src/app/vote/[id]/components/VoteDescription.tsx
apps/jurumarble/src/app/vote/[id]/components/VoteWriterBox.tsx
apps/jurumarble/src/app/vote/page.tsx
apps/jurumarble/src/lib/apis/comment.ts
apps/jurumarble/src/lib/utils/formatUserInfo.ts

- 게시글 내에 유저 프로필 영어로 뜨던것 수정
- 알코올 래밸 추가
- 투표홈 투표수치 안나오던 버그 수정
- 참고 사항1

[JR-867] 유저 프로필 칩 변경

---

apps/jurumarble/src/app/drink-info/[id]/components/DrinkInfoContainer.tsx
apps/jurumarble/src/app/map/components/MapContainer.tsx
apps/jurumarble/src/app/map/page.tsx
apps/jurumarble/src/app/my/edit/services/useEditProfileService.ts
apps/jurumarble/src/app/page.tsx
apps/jurumarble/src/app/vote/[id]/components/Comment.tsx
apps/jurumarble/src/app/vote/[id]/components/VoteAnalyzeBar.tsx
apps/jurumarble/src/app/vote/[id]/components/VoteSmallSelectFilter.tsx
apps/jurumarble/src/app/vote/[id]/page.tsx
apps/jurumarble/src/app/vote/page.tsx
apps/jurumarble/src/app/vote/post/services/usePostVoteService.ts
apps/jurumarble/src/lib/constants.tsx
apps/jurumarble/src/services/useBookmarkService.ts

- 글작성후 투표 리스트 캐싱제거해서 업데이트 되도록수정
- 투표 필터 추가
- 토스트 메시지 하나만 뜨도록 수정
- 술 용량 추가
- 술지도 가끔 안뜨던 버그 수정
- 참고 사항1

[JR-869] 투표홈, 투표 상세 , 술인포, 지도 자체 QA 

---

.github/labeler.yml
.github/workflows/pr-labeler.yml
.pnp.cjs
.yarnrc.yml
apps/jurumarble/next.config.js
yarn.lock

PR 생성시 라벨 붙도록 자동화

---

.pnp.cjs
.yarnrc.yml
apps/jurumarble/next.config.js
apps/jurumarble/src/app/search/components/DrinkItem.tsx
packages/ui/components/index.ts
packages/ui/components/ratioframe/RatioFrame.tsx
packages/ui/components/ratioframe/index.ts
yarn.lock

-  이미지 frame 컴포넌트 구현 및 다운로드 방식 변경

 이미지 frame 컴포넌트 구현 및 다운로드 방식 변경

---

apps/jurumarble/src/lib/styles/global.css

global css 오타 수정

---

.pnp.cjs
apps/jurumarble/package.json
apps/jurumarble/src/lib/apis/vote/getHotDrinkList.ts
apps/jurumarble/src/lib/apis/vote/getHotDrinkVote.ts
apps/jurumarble/src/modules/httpFetch.ts
packages/http-fetch/.eslintrc.js
packages/http-fetch/index.ts
packages/http-fetch/package.json
packages/http-fetch/src/http-fetch.ts
packages/http-fetch/src/index.ts
yarn.lock

아래와 같이 사용하면 됩니다.
```ts
export const httpFetch = createHttpFetch({
baseUrl: SERVER_URL,
});
export const authHttpFetch = createHttpFetch({
baseUrl: SERVER_URL,
interceptors: {
response: async (response) => {
if (response.status === 401) {
const tokens = userStorage.get();
if (!tokens) {
throw new Error("No tokens found");
}
alert("로그인이 만료되었습니다. 다시 로그인해주세요.");
logout();
}
return response;
},
request: async (args) => {
const tokens = userStorage.get();
if (!tokens) {
throw new Error("No tokens found");
}
const { accessToken } = tokens;
if (accessToken) {
args[1] = {
...args[1],
headers: {
...args[1]?.headers,
Authorization: `Bearer ${accessToken}`,
},
};
}
return args;
},
},
});
```

http fetch modules 생성

---

.pnp.cjs
apps/jurumarble/package.json
packages/browser-api/.eslintrc.js
packages/browser-api/index.ts
packages/browser-api/package.json
packages/browser-api/src/cookie.ts
packages/browser-api/src/index.ts
packages/browser-api/src/local-storage.ts
packages/browser-api/src/session-storage.ts
yarn.lock

- cookie, localStorage, sessionStorage는 해당 모듈을 통해 사용해주세요
- 참고 사항1

browser-api 패키지 생성

---

.pnp.cjs
.yarnrc.yml
apps/jurumarble/Dockerfile
apps/jurumarble/package.json
package.json
scripts/docker/docker-compose.yaml
scripts/shell/jurumarble.sh
yarn.lock

- Docker & Docker Compose 세팅
- 서버 실행 방법: `yarn juma:dev`
- Docker Desktop 앱 설치되어있어야함

Docker & Docker Compose 세팅

---

apps/jurumarble/src/app/vote/[id]/components/ChipContainer.tsx
apps/jurumarble/src/app/vote/[id]/components/Comment.tsx
apps/jurumarble/src/app/vote/[id]/components/CommentContainer.tsx
apps/jurumarble/src/app/vote/[id]/components/VoteAnalyzeBar.tsx
apps/jurumarble/src/app/vote/[id]/components/VoteDescription.tsx
apps/jurumarble/src/app/vote/hooks/useFlipAnimation.ts
apps/jurumarble/src/app/vote/page.tsx

- 키보드 인터렉션 변경
- 투표 두줄 제한
- 댓글 컬러변경 (투표 , 인포)
- 온보딩 킬수 잇는 아이콘추가
- 참고 사항1

[JR-886] QA2

---

apps/jurumarble/src/app/map/components/MapContainer.tsx
apps/jurumarble/src/app/map/services/useDrinksMapService.ts

- 지도에 오버레이를 추가하고 클릭 이벤트를 추가합니다
- 참고 사항1

[JR-889] 지도 오버레이 추가
